### ISSUE TITLE
Add Mimir Integration

### ISSUE THREAD

**Issue by sourabhbhandari** [DrDroidLab/PlayBooks#104]
## What new integration do you require?

we use grafana mimir to store and query metrics.
Having an integration for mimir with Playbook will help us add more context during investigation of an issue.

## Additional context
Add any other context about the new integration here.

#### *Thank you* for your new integration request!

**Comment by dimittal** [comment]
PR -> https://github.com/DrDroidLab/PlayBooks/pull/118
