### ISSUE TITLE
Allow user to fetch metrics from Google Cloud

### ISSUE THREAD

**Issue by dimittal** [DrDroidLab/PlayBooks#194]
## What new integration do you require?
Allow user to fetch metrics from Google Cloud

## Describe what all querying / actions you need to perform with this integration
Need to query metrics of Google cloud services like DB, VMs.

#### *Thank you* for your new integration request!

**Comment by droid-mohit** [comment]
Changes for this feature can be found in the following PR: 

- https://github.com/DrDroidLab/PlayBooks/pull/320
- https://github.com/DrDroidLab/PlayBooks/pull/329
- https://github.com/DrDroidLab/PlayBooks/pull/326

**Comment by droid-mohit** [comment]
This is released.
