### ISSUE TITLE
Allow user to fetch logs from Google Cloud

### ISSUE THREAD

**Issue by droid-mohit** [DrDroidLab/PlayBooks#224]
## What new integration do you require?

*Please describe.*
Allow user to fetch logs from Google Cloud.

## Describe what all querying / actions you need to perform with this integration
Need to query logs from Google cloud logging.

## Additional context
Add any other context about the new integration here.

#### *Thank you* for your new integration request!

**Comment by vpavankalyan** [comment]
Hi @droid-mohit, 
I would love to contribute. 
Can u help me understand the issue better and any approaches you have in mind to go about it.

**Comment by droid-mohit** [comment]
Hi @vpavankalyan,

Thank you for your interest. This issue aims to bring google cloud logging as an integration source. Allowing users to query logs as part of debugging steps in their playbooks. 

The platform connects and interacts with different sources via REST APIs. 
As a starting point here is the Google Cloud logging API documentation: https://cloud.google.com/logging/docs/reference/v2/rest

You can join our slack community and we can discuss further on this.

**Comment by droid-mohit** [comment]
Changes for this feature can be found in the following PR: 

- https://github.com/DrDroidLab/PlayBooks/pull/320
- https://github.com/DrDroidLab/PlayBooks/pull/329
- https://github.com/DrDroidLab/PlayBooks/pull/326

**Comment by droid-mohit** [comment]
This is released.
