### ISSUE TITLE
remote server  inventory or input text can be write

### ISSUE THREAD

**Issue by rookie-man-fack** [DrDroidLab/PlayBooks#236]
We hope to change the remote server field to be an input field or create a dropdown list similar to an Ansible inventory. In most cases, we have only one PEM file, but there may be many corresponding servers. This would avoid having to repeatedly add the PEM file.

![2024-06-11 04 26 42](https://github.com/DrDroidLab/PlayBooks/assets/110986345/f0d137a0-b2b1-4a5b-b9ce-c2463df05532)

**Comment by dimittal** [comment]
We have taken this up for our next sprint @rookie-man-fack. That should allow you to mention multiple user@hostname while adding PEM file so that this becomes a drop-down. Additionally you would be able to type it in & it should work as long as the PEM file works for it.

**Comment by rookie-man-fack** [comment]
Thank you very much for your answer发自我的 iPhone在 2024年6月11日，16:52，Dipesh Mittal ***@***.***> 写道：﻿
We have taken this up for our next sprint @rookie-man-fack. That should allow you to mention multiple ***@***.*** while adding PEM file so that this becomes a drop-down. Additionally you would be able to type it in & it should work as long as the PEM file works for it.

**Comment by dimittal** [comment]
Hi @rookie-man-fack we release change last week to allow a comma separated entry into the remote server data source for the same key in the format of username@hostname and then this will be available in a drop-down during configuration of playbook step. You can also enter a custom entry also during configuration.

**Comment by droid-mohit** [comment]
Development of this feature is done and is available in latest stable release.

PR: https://github.com/DrDroidLab/PlayBooks/pull/253
