### ISSUE TITLE
Update postgres test connection form

### ISSUE THREAD

**Issue by droid-mohit** [DrDroidLab/PlayBooks#27]
Currently postgres allows only host name, user and password in the config form. Update it to take port and database as well.

**Comment by sidPhoenix17** [comment]
Can we add two more related tasks in this ticket?

* Add the integrations for JDBC compatible DBs (via connection string).
* Credentials are visible for Postgres currently after saving.

**Comment by droid-mohit** [comment]
Noted, will release a fix for all all 3 issues and JDBC connection string connector as part of new feature.

**Comment by droid-mohit** [comment]
We have released a fix for these.
