### ISSUE TITLE
Capability to send email through playbook.

### ISSUE THREAD

**Issue by kutbuddin-prodigal** [DrDroidLab/PlayBooks#299]
## What new integration do you require?

Need functionality to send email notifications.

## Describe what all querying / actions you need to perform with this integration

Send emails to configured email id with configurable message body, recipients.

## Do your need this integration to start using Playbooks or expand your usage?

expand our usage

#### *Thank you* for your new integration request!

**Comment by dimittal** [comment]
Adding details on what this change will include:

- Allow Email SMTP server configuration as an integration

- Add following fields when configuring an email task
  - To (comma separated)
  - Cc (comma separated)
  - Body (wysiwyg editor)
  - Give option to add other step results (multi drop-down for selecting tasks or select all)

**Comment by droid-mohit** [comment]
This is released. Changes for the same can be found here: https://github.com/DrDroidLab/PlayBooks/pull/348
