### ISSUE TITLE
Context Propagation across workflow and playbooks

### ISSUE THREAD

**Issue by sidPhoenix17** [DrDroidLab/PlayBooks#301]
## Is your feature request related to a problem?
No
*Please describe.*

## Describe the solution you'd like

Details here -- https://github.com/DrDroidLab/PlayBooks/discussions/265

**Comment by droid-mohit** [comment]
Changes for this feature can be found here: https://github.com/DrDroidLab/PlayBooks/pull/330/files

**Comment by droid-mohit** [comment]
This is released.
