### ISSUE TITLE
Integration with self-managed Kubernetes clusters

### ISSUE THREAD

**Issue by dashashutosh24** [DrDroidLab/PlayBooks#319]
## What new integration do you require?

Integration with self-managed K8s clusters besides AKS, GKE and EKS

## Describe what all querying / actions you need to perform with this integration

To allow insights into self managed k8s clusters, such as logs and events for different resources and setup playbooks based on the findings, DrDroid can be configured either with a ServiceAccount token for public URLs of K8s clusters or in case the k8s cluster is behind a firewall (private K8s cluster) and DrDroid is running in the same cluster, maybe DrDroid's role permissions can be updated granting the server permissions to access different resources in the k8s cluster and the server the can leverage the same to expand its visibility over the cluster.

## Do your need this integration to start using Playbooks or expand your usage?

Yes, since many organisations run workloads on on-prem / self-managed k8s clusters, this implementation would help in debugging the k8s workloads much better

## Additional context
Add any other context about the new integration here.

A use case for this integration when coupled with context propagation, is that any alert that might include, for example the pod name, we can have a playbook to capture the pod name from the alert message and then use the integration to fetch the pod logs, describe the pod for more details, check the resource usage and maybe even query metrics datasources  such as prometheus for the specific pod's metrics.

#### *Thank you* for your new integration request!

**Comment by droid-mohit** [comment]
We have released this. Changes for the same can be found here: https://github.com/DrDroidLab/PlayBooks/pull/351
