### ISSUE TITLE
Enable creation of multiple connections of same integration type

### ISSUE THREAD

**Issue by dimittal** [DrDroidLab/PlayBooks#83]
Allow multiple databases and other sources be connected instead of one per integration type.

**Comment by chinaran** [comment]
+1

**Comment by droid-mohit** [comment]
Changes for this issue can be tracked in this PR: https://github.com/DrDroidLab/PlayBooks/pull/139

**Comment by droid-mohit** [comment]
This is released, closing the ticket.
