### ISSUE TITLE
Add integration for Azure Log Analytics

### ISSUE THREAD

**Issue by Sandy247** [DrDroidLab/PlayBooks#84]
We are an Azure-based platform and send our logs to Azure log analytics. Our pipelines are orchestrated using Azure Data Factory. To build and run our playbooks, we would need to support for the above services.

**Comment by sidPhoenix17** [comment]
Hey @Sandy247 thanks for the request! Couple of ideas:
* We have an integration for querying CloudWatch Logs from a playbook. Do you think something similar would be helpful for Azure Log Analytics? We plan to use [these rest apis](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/overview) for the implementation.

* Here are the [endpoints](https://learn.microsoft.com/en-us/rest/api/datafactory/pipelines?view=rest-datafactory-2018-06-01) that we would be using for Azure Data Factory (ADF).

If you have any specific pointers on what integration use-cases (e.g. checking pipeline run in ADF) would be most helpful?

**Comment by droid-mohit** [comment]
Splitting this issue into 2. One for Azure log analytics and and for Azure Data Factory, which can be tracked [here](https://github.com/DrDroidLab/PlayBooks/issues/215).

**Comment by droid-mohit** [comment]
Changes for Azure Log Analytics can be found here: https://github.com/DrDroidLab/PlayBooks/pull/101
