### ISSUE TITLE
Request for integration with Honeycomb

### ISSUE THREAD

**Issue by AkshayD110** [DrDroidLab/PlayBooks#91]
## Is your feature request related to a problem?

We use honeycomb as our observability tool for Trace currently. 
Having an integration for Honeycomb with Playbook will help us  add more context during investigation of an issue. 

## Describe the solution you'd like
We would like to have an integration of playbook with Honeycomb

## Describe alternatives you've considered
We currently don't use Playbook with Honeycomb as there isn't an integration available.

**Comment by dimittal** [comment]
Hey @AkshayD110,
I am working on this issue. I have 2 questions that will help me assess the priority for this.
1. What are you looking to query from Honeycomb as part of a Playbook? 
2. Is your organisation using Enterprise version for Honeycomb? Currently, they allow querying the traces data via an API only in their Enterprise version. 

Thanks

**Comment by sidPhoenix17** [comment]
Closing this for now as we couldn't get a sandbox for Honeycomb to test out the APIs. If anyone is interested to pick this up or request this, please re-open it.
